hw2
================
Yiran Jin
2026-10-05

load necessary libraries

``` r
library(tidyverse) 
```

    ## Warning: package 'ggplot2' was built under R version 4.4.3

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   4.0.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.4     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

# Problem 1

``` r
subway_data = read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>     clean_names() |> 
  select(
    line, 
    station_name, 
    station_latitude, 
    station_longitude, 
    starts_with("route"), 
    entrance_type, 
    entry, 
    vending, 
    ada
  ) |> 
  mutate(
    entry = case_match(
      entry, 
      "YES" ~ TRUE, 
      "NO" ~ FALSE 
    ) 
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## summary of the data

This NYC transit dataset contains information about NYC subway stations
and their entrances and exits. The variables include the subway line,
station name, station latitude and longitude, routes served, entrance
type, whether entry is allowed, whether vending is available, and ADA
compliance. I selected the variables which are needed and converted the
entry variable from character values (YES and NO) to a logical variable
(TRUE and FALSE). The resulting dataset has 1868 rows and 19 columns.
These data are not tidy because the routes served by each station are
stored in multiple variables rather than having one route per
observation. For example, 36th St serves both the N and R trains, which
are stored in separate variables (route1 and route2) rather than as
separate observations.

## answers of the questions

### distinct stations (only keep the first row of each distinct line and station name)

``` r
subway_data |> 
  distinct(line, station_name) |> 
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

### ADA Compliant Stations

``` r
subway_data |> 
  filter(ada == TRUE) |> 
  distinct(line, station_name) |> 
  nrow()
```

    ## [1] 84

There are 84 ADA-compliant stations.

### Entrances/exits Without Vending That Allow Entrance

``` r
subway_data |> 
  filter(vending == "NO") |> 
  summarize( 
    proportion = mean(entry, na.rm = TRUE) 
  )
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1      0.377

Among station entrances and exits without vending, approximately 37.7%
allow entrance.

## Reformat Route Variables

``` r
subway_routes =
  subway_data |>
  mutate(
    across(starts_with("route"), as.character)
  ) |>
  pivot_longer(
    cols = starts_with("route"),
    names_to = "route_number",
    values_to = "route_name",
    values_drop_na = TRUE
  ) |>
  filter(route_name != "")
```

## Stations Serving the A Train

``` r
subway_routes |> 
  filter(route_name == "A") |> 
  distinct(line, station_name) |> 
  nrow()
```

    ## [1] 60

There are 60 distinct stations that serve the A train.

## ADA-Compliant A Train Stations

``` r
subway_routes |> 
  filter(route_name == "A", ada == TRUE) |> 
  distinct(line, station_name) |> 
  nrow()
```

    ## [1] 17

17 are ADA compliant

# Problem 2

## clean the data–Mr. Trash Wheel

``` r
library(readxl)

mr_trash_wheel =
  read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N709"
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year = as.integer(year),
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )
```

## clean the data–Professor Trash Wheel

``` r
professor_trash_wheel =
  read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:L134"
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year = as.integer(year),
    trash_wheel = "Professor Trash Wheel"
  )
```

## clean the data–Gwynnda

``` r
gwynnda_trash_wheel =
  read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynns Falls Trash Wheel",
    range = "A2:L350"
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    trash_wheel = "Gwynnda"
  )
```

## Combine the datasets

``` r
trash_wheel =
  bind_rows(
    mr_trash_wheel,
    professor_trash_wheel,
    gwynnda_trash_wheel
  )
```

## Summary of the data

The Trash Wheel dataset contains information on dumpsters collected by
three trash wheels: Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda.
Key variables include the dumpster number, month, year, date, weight and
volume of trash collected, and counts of different types of trash such
as plastic bottles, polystyrene, cigarette butts, plastic bags, and
wrappers. I cleaned each dataset by selecting the appropriate worksheet
and data range, removing rows that did not contain dumpster-specific
observations, and using reasonable variable names. For Mr. Trash Wheel,
I also rounded the number of sports balls to the nearest integer and
converted it to an integer variable. I changed ‘years’ column to integer
for each dataset in order to combine three datasets. Finally, I added a
variable identifying the trash wheel and combined the three datasets
into one tidy dataset. The resulting dataset contains 1187 observations.

## total weight of trash collected by Professor Trash Wheel

``` r
professor_trash_wheel |>
  summarize(
    total_weight = sum(weight_tons, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         282.

Professor Trash Wheel collected a total of 282.26 tons of trash.

## total number of cigarette butts collected by Gwynnda in June of 2022

``` r
gwynnda_trash_wheel |>
  filter(
    month == "June",
    year == 2022
  ) |>
  summarize(
    total_cigarette_butts = sum(cigarette_butts, na.rm = TRUE)
  )
```

    ## # A tibble: 1 × 1
    ##   total_cigarette_butts
    ##                   <dbl>
    ## 1                 18120

Gwynnda collected a total of 18,120 cigarette butts in June 2022
